# Generated by Django 6.0.3 on 2026-03-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Stuck', 'Stuck'), ('Working on it', 'Working on it'), ('Done', 'Done')], default='Stuck', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Stuck', 'Stuck'), ('Working on it', 'Working on it'), ('Done', 'Done')], default='Stuck', max_length=50),
        ),
    ]
