# Generated by Django 6.0.2 on 2026-03-19 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_subtask_task_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['-level'], 'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#64748b', max_length=7),
        ),
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.CharField(default='#64748b', max_length=7),
        ),
        migrations.AddField(
            model_name='priority',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Stuck', 'Stuck'), ('Working on it', 'Working on it'), ('Done', 'Done')], default='Stuck', max_length=50),
        ),
    ]
