# Generated by Django 6.0.2 on 2026-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_note_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Starting', 'Starting'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Done', 'Done')], default='Starting', max_length=50),
        ),
    ]
