# Generated by Django 6.0.3 on 2026-03-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_category_id_alter_note_id_alter_priority_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress ', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
