# Generated by Django 6.0.3 on 2026-03-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='status',
            new_name='is_completed',
        ),
    ]
